### ISSUE TITLE
Create ADR check

### ISSUE THREAD

**Issue by Entreco** [Entreco/forex_ea#10]
No clue what ADR is?

**Comment by rjmjanssen** [comment]
- Create simple ADR (Average Daily Range) BBand based on PERIOD_D1 timeframe. 
- Make the Period and Sigma as parameters. Period default=7 and Sigma default=2
- When  ADR for day of trading session is ABOVE BBand Upper, pair does not trade and is assigned volume 0.01 (similar to pair thats in negative profit in lotcalcalculator)

**Comment by Entreco** [comment]
> When ADR for day of trading session is ABOVE BBand Upper, pair does not trade...

Does that mean:
```
if(adrBase > bbUpper || adrBase < bbLower){
   // cancel also all pending orders for that pair?
}
```

Right now, I have something like this, where adrHandle is the handle to a BollingerBand with D1, p=7 and s=2

```
//--- Extract ADR variables
   const double adrUpper = NormalizeDouble(UpperBand(1, adrHandle),symbolDigits);
   const double adrLower = NormalizeDouble(LowerBand(1, adrHandle), symbolDigits);
   const double adrBase = NormalizeDouble(BaseBand(1, adrHandle), symbolDigits);
   if(adrBase > upper || adrBase < lower)
     {
      CancelPendingOrders();
      return;
     }
//--- End of ADR check logic
````

**Comment by rjmjanssen** [comment]
Heb even gekeken maar toch nog een paar fundamentale dingen die niet kloppen
- ADR (average DAILY range) moet bekeken worden over gisteren tot en met dag XX(bv 7) geleden. Van die 6 dagen, daar maak je een BBand van. Daarna ga je kijken of de ADR van VANDAAG, boven die Bband upper valt. ZO JA, block je het traden. Je gaat niet kijken of ie er onder valt, dat is NIET belangrijk
- -> Dus dit klopt zo niet: if(AdrPeriod==0 || (bidask.base <= adr.upper && bidask.base >= adr.lower))
- -> Moet zijn: if(AdrPeriod==0 || TODAYS_ADR <= adr.upper). Je pakt hiervoor niet de AVERAGED ADR (ADR.base), maar de ruwe ADR van vandaag. Deze is high-low voor de daily candle
- - Even goed zorgen dat de ADR BBand als periode PERIOD_D1 gebruikt en NIET PERIOD_M5 vermenigvuldigt met 288
-  Misschien dat je beter ATR kunt gebruiken als ADR. Hiervoor even dit lezen: https://www.niftyscalper.com/blogs/2018/11/11/atr-average-true-range-vs-adr-average-day-range-what-they-dont-tell-you
